CONFIG_BOOTCOMMAND="run findfdt;mmc dev ${mmcdev};mmc dev ${mmcdev}; if mmc rescan; then if run loadbootscript; then run bootscript; else if run loadimage; then run mmcboot; else run netboot; fi; fi; else run netboot; fi"
CONFIG_IMX_CONFIG="board/freescale/mx7dsabresd/imximage.cfg"
CONFIG_SYS_FSL_ESDHC_ADDR=0
CONFIG_IS_MODULE(option)="config_enabled(CONFIG_VAL(option ##_MODULE))"
CONFIG_SYS_LOAD_ADDR=$(CONFIG_LOADADDR)
CONFIG_SYS_FSL_MAX_NUM_OF_SEC=y
CONFIG_SYS_HELP_CMD_WIDTH=10
CONFIG_SYS_CBSIZE=2048
CONFIG_SC_TIMER_CLK=8000000
CONFIG_SYS_FSL_SEC_ADDR="(CAAM_IPS_BASE_ADDR + CONFIG_SYS_FSL_SEC_OFFSET)"
CONFIG_ENV_OVERWRITE=y
CONFIG_SYS_MALLOC_LEN="(32 * SZ_1M)"
CONFIG_SYS_MMC_ENV_DEV=0
CONFIG_SYS_I2C_SPEED=100000
CONFIG_SYS_BOOTM_LEN=0x1000000
CONFIG_SYS_AUXCORE_BOOTDATA=0x7F8000
CONFIG_MXC_UART=y
CONFIG_SYS_BARGSIZE=$(CONFIG_SYS_CBSIZE)
CONFIG_IS_BUILTIN(option)="config_enabled(CONFIG_VAL(option))"
CONFIG_MXC_USB_PORTSC="(PORT_PTS_UTMI | PORT_PTS_PTW)"
CONFIG_SYS_FSL_CLK=y
CONFIG_SYS_FSL_JR0_ADDR="(CONFIG_SYS_FSL_SEC_ADDR + CONFIG_SYS_FSL_JR0_OFFSET)"
CONFIG_SYS_MAXARGS=32
CONFIG_EXTRA_ENV_SETTINGS="UPDATE_M4_ENV CONFIG_MFG_ENV_SETTINGS TEE_ENV CONFIG_DFU_ENV_SETTINGS "script=boot.scr0image=zImage0console=ttymxc00fdt_high=0xffffffff0initrd_high=0xffffffff0fdt_file=undefined0fdt_addr=0x830000000tee_addr=0x840000000tee_file=uTee-7dsdb0boot_fdt=try0ip_dyn=yes0splashimage=0x8c0000000mmcdev=__stringify(CONFIG_SYS_MMC_ENV_DEV)"0mmcpart=" __stringify(CONFIG_SYS_MMC_IMG_LOAD_PART) "0mmcroot=" CONFIG_MMCROOT " rootwait rw0mmcautodetect=yes0mmcargs=setenv bootargs console=${console},${baudrate} root=${mmcroot}0loadbootscript=fatload mmc ${mmcdev}:${mmcpart} ${loadaddr} ${script};0bootscript=echo Running bootscript from mmc ...; source0loadimage=fatload mmc ${mmcdev}:${mmcpart} ${loadaddr} ${image}0loadfdt=fatload mmc ${mmcdev}:${mmcpart} ${fdt_addr} ${fdt_file}0loadtee=fatload mmc ${mmcdev}:${mmcpart} ${tee_addr} ${tee_file}0mmcboot=echo Booting from mmc ...; run mmcargs; if test ${tee} = yes; then run loadfdt; run loadtee; bootm ${tee_addr} - ${fdt_addr}; else if test ${boot_fdt} = yes || test ${boot_fdt} = try; then if run loadfdt; then bootz ${loadaddr} - ${fdt_addr}; else if test ${boot_fdt} = try; then bootz; else echo WARN: Cannot load the DT; fi; fi; else bootz; fi; fi;0netargs=setenv bootargs console=${console},${baudrate} root=/dev/nfs ip=dhcp nfsroot=${serverip}:${nfsroot},v3,tcp0netboot=echo Booting from net ...; run netargs; if test ${ip_dyn} = yes; then setenv get_cmd dhcp; else setenv get_cmd tftp; fi; ${get_cmd} ${image}; if test ${tee} = yes; then ${get_cmd} ${tee_addr} ${tee_file}; ${get_cmd} ${fdt_addr} ${fdt_file}; bootm ${tee_addr} - ${fdt_addr}; else if test ${boot_fdt} = yes || test ${boot_fdt} = try; then if ${get_cmd} ${fdt_addr} ${fdt_file}; then bootz ${loadaddr} - ${fdt_addr}; else if test ${boot_fdt} = try; then bootz; else echo WARN: Cannot load the DT; fi; fi; else bootz; fi; fi;0findfdt=if test $fdt_file = undefined; then setenv fdt_file imx7d-sdb.dtb; fi;0"
CONFIG_BOARDDIR="board/freescale/mx7dsabresd"
CONFIG_SYS_MAX_FLASH_SECT=512
CONFIG_DFU_ENV_SETTINGS="dfu_alt_info=image raw 0 0x800000;u-boot raw 0 0x4000;bootimg part 0 1;rootfs part 0 20"
CONFIG_LOADADDR=0x80800000
CONFIG_ETHPRIME="eth0"
CONFIG_ARMV7_SECURE_BASE=0x00900000
CONFIG_SYS_FSL_SEC_OFFSET=0
CONFIG_SYS_MMC_IMG_LOAD_PART=y
CONFIG_SYS_INIT_RAM_SIZE="IRAM_SIZE"
CONFIG_MXC_GPT_HCLK=y
CONFIG_SYS_BAUDRATE_TABLE="{ 9600, 19200, 38400, 57600, 115200 }"
CONFIG_VAL(option)="config_val(option)"
CONFIG_SYS_SDRAM_BASE="PHYS_SDRAM"
CONFIG_SYS_INIT_SP_OFFSET="(CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)"
CONFIG_SYS_INIT_RAM_ADDR="IRAM_BASE_ADDR"
CONFIG_SYS_INIT_SP_ADDR="(CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)"
CONFIG_IMX_THERMAL=y
CONFIG_MXC_UART_BASE="UART1_IPS_BASE_ADDR"
CONFIG_SYS_BOOT_RAMDISK_HIGH=y
CONFIG_SYS_FSL_USDHC_NUM=2
CONFIG_IOMUX_LPSR=y
CONFIG_SYS_MMC_ENV_PART=0
CONFIG_CMD_READ=y
CONFIG_ARMV7_PSCI_1_0=y
CONFIG_SYS_MEMTEST_END="(CONFIG_SYS_MEMTEST_START + 0x20000000)"
CONFIG_SYS_PBSIZE="(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)"
CONFIG_MMCROOT="/dev/mmcblk0p2"
CONFIG_SYS_MEMTEST_START=0x80000000
CONFIG_LMB=y
CONFIG_SYS_I2C_MXC=y
CONFIG_IS_ENABLED(option)="(config_enabled(CONFIG_VAL(option)) || config_enabled(CONFIG_VAL(option ##_MODULE)))"
CONFIG_SERIAL_TAG=y
CONFIG_MFG_ENV_SETTINGS="CONFIG_MFG_ENV_SETTINGS_DEFAULT "initrd_addr=0x868000000initrd_high=0xffffffff0emmc_dev=20sd_dev=00mtdparts= MFG_NAND_PARTITION "0"
CONFIG_MFG_ENV_SETTINGS_DEFAULT=""mfgtool_args=setenv bootargs console=${console},${baudrate} rdinit=/linuxrc clk_ignore_unused 0kboot="MFG_BOOT_CMD"0bootcmd_mfg=run mfgtool_args;if iminfo ${initrd_addr}; then if test ${tee} = yes; then bootm ${tee_addr} ${initrd_addr} ${fdt_addr}; else " MFG_BOOT_CMD "${loadaddr} ${initrd_addr} ${fdt_addr}; fi; else " FASTBOOT_CMD "fi;0" MFG_NAND_FIT_PARTITION"
CONFIG_SYS_FSL_JR0_OFFSET=0x1000
